### ISSUE TITLE
Error while gulping

### ISSUE THREAD

**Issue by commwork** [ahmadawais/advanced-gulp-wordpress#3]
When I type "gulp" he starts and stops with the following error (
When I remove "gulp-autoprefixer" from the gulpfile.js it works without errors.):

`buffer.js:167
  throw new TypeError('must start with number, buffer, array or string');
  ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at Transform.transform [as _transform](C:xampphtdocsdodowp-contentthemesdodonode_modulesgulp-combine-media-queriesindex.js:152:21)
    at Transform._read (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\gulp-combine-media-queries\node_modules\readable-stream\lib_stream_transform.js:184:10)
    at Transform._write (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\gulp-combine-media-queries\node_modules\readable-stream\lib_stream_transform.js:172:12)
    at doWrite (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\gulp-combine-media-queries\node_modules\readable-stream\lib_stream_writable.js:237:10)
    at writeOrBuffer (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\gulp-combine-media-queries\node_modules\readable-stream\lib_stream_writable.js:227:5)
    at Transform.Writable.write (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\gulp-combine-media-queries\node_modules\readable-stream\lib_stream_writable.js:194:11)
    at StreamFilter.ondata (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\readable-stream\lib_stream_readable.js:531:20)
    at emitOne (events.js:77:13)
    at StreamFilter.emit (events.js:169:7)
    at readableAddChunk (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\readable-stream\lib_stream_readable.js:198:18)
    at StreamFilter.Readable.push (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\readable-stream\lib_stream_readable.js:157:10)
    at StreamFilter.Transform.push (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\readable-stream\lib_stream_transform.js:123:32)
    at StreamFilterCallback (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\streamfilter\src\index.js:30:15)
    at streamfilter.objectMode (C:\xampp\htdocs\dodo\wp-content\themes\dodo\node_modules\gulp-filter\index.js:19:3)`

I updated gulp-autoprefixer to the newest version but still there is the error.
Windows 10, NPM v. 3.82, gulp CLI version 1.2.1.

**Comment by ahmadawais** [comment]
@commwork I would recommend you to use [WPGulp](https://github.com/ahmadawais/WPGulp) instead of this repo, since WPGulp is much better maintained and has almost all the features this repo has. Sooner than later, I will make this one similar to that and might depricate it. 

The issue might be due to the old versions of plugins in package.json and stuff like that. There is no reason for me to recommend this repo over WPGulp, do you have any?

**Comment by ahmadawais** [comment]
The issue might be due to the old versions of plugins in package.json and stuff like that. There is no reason for me to recommend this repo over WPGulp, do you have any?

**Comment by commwork** [comment]
Hmm, no, just wanted to test it and read a little of your code because it's poetry ;).

**Comment by ahmadawais** [comment]
:100: WPGulp is the newer version of this repo :)

**Comment by thomasmodeneis** [comment]
I would be really nice to advise people that this repo is no longer maintained and that this issue may happen, just as just happen to be for me.
Cheers.

**Comment by ahmadawais** [comment]
@thomasmodeneis I have done that in the repo's description.

![](https://i.imgur.com/ZYiZift.png)

I do guide everyone who opens up an issue. Since I didn't collect the emails, I can't inform everyone about it. I am open to suggestions. 

This repo is not being maintained but the workflow most certainly is. More than 200 devs are using [WPGulp](https://github.com/ahmadawais/WPGulp).
